In [1]:
import numpy as np

In [3]:
vector = np.array([-50, -25, 0, 25, 100, -300])
norma_0 = np.linalg.norm(vector, ord=0)
norma_0

5.0

In [6]:
A = np.array([[7, -1], [3, -1]])
b = np.array([-2, -5])

x = np.linalg.solve(A, b)
x

array([0.75, 7.25])

In [8]:
A = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)
B = np.array(
    [[3, 2],
    [4, 5],
    [1, 2]]
)

C = A.dot(B)
D = B.dot(A)

C, ".......", D

(array([[14, 18],
        [38, 45]]), '.......', array([[11, 16, 21],
        [24, 33, 42],
        [ 9, 12, 15]]))

In [9]:
A = np.array(
    [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
)

A.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [10]:
def angle_between(v1, v2):
    dot_pr = v1.dot(v2)
    norms = np.linalg.norm(v1) * np.linalg.norm(v2)
 
    return np.rad2deg(np.arccos(dot_pr / norms))

a = np.array([0, 1])
b = np.array([1, 0])

print(angle_between(a, b))

90.0


In [12]:
M = np.array(
    [[1, 3],
    [5, 6]]
)
v = np.array([[3], [3]])

A = M + 3
B = M + v

A, B

(array([[4, 6],
        [8, 9]]), array([[4, 6],
        [8, 9]]))

In [14]:
M2 = np.array(
    [[1, 0],
    [0, 1]]
)
M3 = np.array(
    [[3, 1],
    [2, 1]]
)

A = M.dot(M2)
B = M2.dot(M)
C = M.dot(M3)
D = M3.dot(M)

A, B, C, D

(array([[1, 3],
        [5, 6]]), array([[1, 3],
        [5, 6]]), array([[ 9,  4],
        [27, 11]]), array([[ 8, 15],
        [ 7, 12]]))

In [16]:
V = np.array([1/2, 1/2, 1/2, 1/2])
np.linalg.norm(V)

1.0

In [19]:
M = np.array(
    [[7, -7, 3],
    [1, 1, 0],
    [0, 0, 1]]
)

V_1 = M[0, :].dot(M[1, :])
V_2 = M[1, :].dot(M[2, :])
V_3 = M[2, :].dot(M[0, :])
V_4 = M[2, :].dot(M[0, :])
V_1, V_2, V_3, V_4

(0, 0, 3, 3)

In [20]:
M = np.array(
    [[1,0,0,0,0],
    [0,2,0,0,0],
    [0,0,3,0,0],
    [0,0,0,4,0],
    [0,0,0,0,5]]
)

1 * 2 * 3 * 4 * 5

120

In [22]:
M = np.array(
    [[1, 2],
    [4, 5],
    [3, 2]]
)
V = np.array([1, 2])

N = M.dot(V)

N

array([ 5, 14,  7])